In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import statsmodels.api as sm

In [2]:
os.chdir('C:\\Users\\USER\\Downloads\\Batch 98 Day 33\\CS 29 Ans -Multiple Linear Regression')

In [3]:
df = pd.read_excel('Health_Score.xlsx')

In [4]:
df.head()

Birth Rate  No of Hospitlas  No of Doctors  Annual Income  \
0         8.0               78            284            9.1   
1         9.3               68            433            8.7   
2         7.5               70            739            7.2   
3         8.9               96           1792            8.9   
4        10.2               74            477            8.3   

   Population Density  
0                 109  
1                 144  
2                 113  
3                  97  
4                 206

In [5]:
X = df.iloc[:,1:].values
X

array([[  78.        ,  284.        ,    9.10000038,  109.        ],
       [  68.        ,  433.        ,    8.69999981,  144.        ],
       [  70.        ,  739.        ,    7.19999981,  113.        ],
       [  96.        , 1792.        ,    8.89999962,   97.        ],
       [  74.        ,  477.        ,    8.30000019,  206.        ],
       [ 111.        ,  362.        ,   10.89999962,  124.        ],
       [  77.        ,  671.        ,   10.        ,  152.        ],
       [ 168.        ,  636.        ,    9.10000038,  162.        ],
       [  82.        ,  329.        ,    8.69999981,  150.        ],
       [  89.        ,  634.        ,    7.5999999 ,  134.        ],
       [ 149.        ,  631.        ,   10.80000019,  292.        ],
       [  60.        ,  257.        ,    9.5       ,  108.        ],
       [  96.        ,  284.        ,    8.80000019,  111.        ],
       [  83.        ,  603.        ,    9.5       ,  182.        ],
       [ 130.        ,  686.      

In [6]:
y = df.iloc[:,0].values
y

array([ 8.        ,  9.30000019,  7.5       ,  8.89999962, 10.19999981,
        8.30000019,  8.80000019,  8.80000019, 10.69999981, 11.69999981,
        8.5       ,  8.30000019,  8.19999981,  7.9000001 , 10.30000019,
        7.4000001 ,  9.60000038,  9.30000019, 10.60000038,  9.69999981,
       11.60000038,  8.10000038,  9.80000019,  7.4000001 ,  9.39999962,
       11.19999981,  9.10000038, 10.5       , 11.89999962,  8.39999962,
        5.        ,  9.80000019,  9.80000019, 10.80000019, 10.10000038,
       10.89999962,  9.19999981,  8.30000019,  7.30000019,  9.39999962,
        9.39999962,  9.80000019,  3.5999999 ,  8.39999962, 10.80000019,
       10.10000038,  9.        , 10.        , 11.30000019, 11.30000019,
       12.80000019, 10.        ,  6.69999981])

In [7]:
df.shape

(53, 5)

In [8]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

print('x_shape :',X.shape)
print('x_train_shape :',X_train.shape)
print('x_test_shape :',X_test.shape)
print('y_shape :',y.shape)
print('y_train_shape :',y_train.shape)
print('y_test_shape :',y_test.shape)


x_shape : (53, 4)
x_train_shape : (42, 4)
x_test_shape : (11, 4)
y_shape : (53,)
y_train_shape : (42,)
y_test_shape : (11,)


In [9]:
regressor = LinearRegression()
regressor.fit(X_train,y_train)
y_pred = regressor.predict(X_test)

In [10]:
y_pred

array([ 8.65654845, 10.57049948,  9.12926103,  9.56518501,  9.15397193,
       10.19763099,  9.00579912, 10.3654805 ,  7.50633246,  9.20384247,
        6.60848831])

In [11]:
y_test

array([ 5.        ,  7.5       , 10.        ,  9.80000019,  9.80000019,
        9.        , 10.10000038,  9.39999962, 10.10000038,  9.69999981,
        8.5       ])

In [12]:
df_y_test= pd.DataFrame(y_test, columns = ['Birth Rate'])
df_y_test_pred =  pd.DataFrame(y_pred, columns = ['Prediction'])
df_diff =df_y_test- df_y_test_pred
y_test_pred = pd.concat ([df_y_test, df_y_test_pred ],axis =1)
y_test_pred['Difference'] =df_y_test ['Birth Rate']- df_y_test_pred['Prediction']

print (y_test_pred)


    Birth Rate  Prediction  Difference
0          5.0    8.656548   -3.656548
1          7.5   10.570499   -3.070499
2         10.0    9.129261    0.870739
3          9.8    9.565185    0.234815
4          9.8    9.153972    0.646028
5          9.0   10.197631   -1.197631
6         10.1    9.005799    1.094201
7          9.4   10.365480   -0.965481
8         10.1    7.506332    2.593668
9          9.7    9.203842    0.496157
10         8.5    6.608488    1.891512


In [13]:
accuracy = r2_score(y_test,y_pred)
accuracy

-0.5993833735307756

In [14]:
y_pred = regressor.predict(X)
y_pred

array([ 9.16830283,  9.06981045, 10.57049948, 10.48822982,  8.67884787,
        8.08173424,  8.35938875,  9.24621142,  9.00537556, 10.10924015,
        6.60848831,  8.82039276,  9.4246574 ,  8.32121054,  9.71259243,
        7.66810144,  8.77961834,  8.51753078,  8.92410509,  9.20384247,
       10.56963221, 10.10241672, 10.13597454,  8.75874067,  8.84854448,
        9.62508144,  9.42764107,  8.83119857, 10.3674476 ,  9.07005095,
        8.65654845,  9.15397193,  9.56518501,  9.69600677,  9.00579912,
        9.82073492,  8.2822002 ,  9.85340539,  8.36367688, 10.3654805 ,
        9.32686798,  9.60932803,  9.63004436,  9.60756789, 10.06314535,
        7.50633246, 10.19763099,  9.77649655, 11.13822764, 10.49516297,
       10.83918806,  9.12926103,  9.68587003])

In [15]:
y

array([ 8.        ,  9.30000019,  7.5       ,  8.89999962, 10.19999981,
        8.30000019,  8.80000019,  8.80000019, 10.69999981, 11.69999981,
        8.5       ,  8.30000019,  8.19999981,  7.9000001 , 10.30000019,
        7.4000001 ,  9.60000038,  9.30000019, 10.60000038,  9.69999981,
       11.60000038,  8.10000038,  9.80000019,  7.4000001 ,  9.39999962,
       11.19999981,  9.10000038, 10.5       , 11.89999962,  8.39999962,
        5.        ,  9.80000019,  9.80000019, 10.80000019, 10.10000038,
       10.89999962,  9.19999981,  8.30000019,  7.30000019,  9.39999962,
        9.39999962,  9.80000019,  3.5999999 ,  8.39999962, 10.80000019,
       10.10000038,  9.        , 10.        , 11.30000019, 11.30000019,
       12.80000019, 10.        ,  6.69999981])

In [16]:
y_pred = pd.DataFrame(y_pred,columns= ['Prediction'])
final = pd.concat([df,y_pred], axis =1)
final['Difference'] =final['Birth Rate']- final['Prediction']

In [17]:
final.head()

Birth Rate  No of Hospitlas  No of Doctors  Annual Income  \
0         8.0               78            284            9.1   
1         9.3               68            433            8.7   
2         7.5               70            739            7.2   
3         8.9               96           1792            8.9   
4        10.2               74            477            8.3   

   Population Density  Prediction  Difference  
0                 109    9.168303   -1.168303  
1                 144    9.069810    0.230190  
2                 113   10.570499   -3.070499  
3                  97   10.488230   -1.588230  
4                 206    8.678848    1.521152

In [18]:
accuracy = r2_score(y,y_pred)
accuracy

0.08950585813004241

In [19]:
regressor.coef_

array([ 0.00501226,  0.00064205, -0.62914983, -0.01130558])

In [20]:
regressor.intercept_

15.552576766444297

In [22]:
import statsmodels.api as sm
reg_ols = sm.OLS (endog = y, exog = X)
reg_ols = reg_ols.fit()
print (reg_ols.summary())


                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.954
Model:                            OLS   Adj. R-squared (uncentered):              0.950
Method:                 Least Squares   F-statistic:                              254.2
Date:                Thu, 19 Sep 2024   Prob (F-statistic):                    4.15e-32
Time:                        16:22:35   Log-Likelihood:                         -112.63
No. Observations:                  53   AIC:                                      233.3
Df Residuals:                      49   BIC:                                      241.1
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------