Case Study -6 (CS 35)
Objective:



-	Employ SVM from scikit learn for binary classification.

-	Impact of preprocessing data and hyper paramter search using grid search and random search CV .

Questions:



•	Load the data from “college.csv” that has attributes collected about private and public colleges for a particular year. We will try to predict the private/public status of the college from other attributes.

•	Use LabelEncoder to encode the target variable in to numerical form and split the data such that 20% of the data is set aside for testing.
	
•	Fit a linear svm from scikit learn and observe the accuracy. [Hint: Use Linear SVC]



•	Preprocess the data using StandardScalar and fit the same model again and observe the change in accuracy.

[Hint: Refer to scikitlearn’s preprocessing methods]



•	Use scikit learn’s gridsearch and Random Search CV to select the best hyperparameter for a non-linear SVM, identify the model with best score and its parameters.

[Hint: Refer to model_selection module of Scikit learn]


In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import LinearSVC,SVC
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from sklearn.preprocessing import StandardScaler

In [2]:
os.chdir ('D:\\top mentor assignment\\Batch 98 Day 57\\ML Case Studies with Answer\\CS 35 Ans -Supervised Learnig-6\\')

In [3]:
os.getcwd()

'D:\\top mentor assignment\\Batch 98 Day 57\\ML Case Studies with Answer\\CS 35 Ans -Supervised Learnig-6'

In [4]:
df = pd.read_csv("College.csv")
df.head()

Private  Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
0     Yes  1660    1232     721         23         52         2885   
1     Yes  2186    1924     512         16         29         2683   
2     Yes  1428    1097     336         22         50         1036   
3     Yes   417     349     137         60         89          510   
4     Yes   193     146      55         16         44          249   

   P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0          537      7440        3300    450      2200   70        78   
1         1227     12280        6450    750      1500   29        30   
2           99     11250        3750    400      1165   53        66   
3           63     12960        5450    450       875   92        97   
4          869      7560        4120    800      1500   76        72   

   S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0       18.1           12    7041         60  
1       12.2           16   10527         56  
2       12.9           30    8735         54  
3        7.7           37   19016         59  
4       11.9            2   10922         15

In [5]:
df.shape

(777, 18)

In [6]:
df.columns

Index(['Private', 'Apps', 'Accept', 'Enroll', 'Top10perc', 'Top25perc',
       'F.Undergrad', 'P.Undergrad', 'Outstate', 'Room.Board', 'Books',
       'Personal', 'PhD', 'Terminal', 'S.F.Ratio', 'perc.alumni', 'Expend',
       'Grad.Rate'],
      dtype='object')

In [28]:
X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train.shape)

(621, 17)


In [8]:
classifier = LinearSVC()


classifier.fit(X_train,y_train)

y_predict = classifier.predict(X_test)

print (classifier.score(X_test,y_test))

0.9487179487179487


In [9]:
print(confusion_matrix(y_predict,y_test))

[[ 36   5]
 [  3 112]]


In [10]:
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )

0.9487179487179487


In [11]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.88      0.92      0.90        39
           1       0.97      0.96      0.97       117

    accuracy                           0.95       156
   macro avg       0.93      0.94      0.93       156
weighted avg       0.95      0.95      0.95       156



In [12]:
classifier = SVC(kernel='linear')
classifier.fit(X_train,y_train)
classifier.score(X_test,y_test)

0.9423076923076923

In [26]:
y_predict = classifier.predict(X_test)
print(confusion_matrix(y_predict,y_test))

[[ 33   3]
 [  6 114]]


In [20]:
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )

0.9423076923076923


In [21]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.92      0.85      0.88        39
           1       0.95      0.97      0.96       117

    accuracy                           0.94       156
   macro avg       0.93      0.91      0.92       156
weighted avg       0.94      0.94      0.94       156



In [27]:
classifier = SVC()
classifier.fit(X_train,y_train)
classifier.score(X_test,y_test)

0.9230769230769231

In [30]:
y_predict = classifier.predict(X_test)
print(confusion_matrix(y_predict,y_test))

[[ 33   6]
 [  6 111]]


In [31]:
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )

0.9230769230769231


In [32]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.85      0.85      0.85        39
           1       0.95      0.95      0.95       117

    accuracy                           0.92       156
   macro avg       0.90      0.90      0.90       156
weighted avg       0.92      0.92      0.92       156



In [33]:
scaler = StandardScaler()
X, y = df.iloc[:, 1:].values, df.iloc[:, 0].values
X = scaler.fit_transform(X)

In [34]:
target_encoder = LabelEncoder()
y = target_encoder.fit_transform(y)

In [35]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train.shape)

(621, 17)


In [36]:
classifier = SVC()
classifier.fit(X_train,y_train)
classifier.score(X_test,y_test)

0.9423076923076923

In [37]:
y_predict = classifier.predict(X_test)
print(confusion_matrix(y_predict,y_test))

[[ 32   2]
 [  7 115]]


In [38]:
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )

0.9423076923076923


In [39]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.94      0.82      0.88        39
           1       0.94      0.98      0.96       117

    accuracy                           0.94       156
   macro avg       0.94      0.90      0.92       156
weighted avg       0.94      0.94      0.94       156



In [40]:
C_range = np.logspace(-2, 10, 13)
gamma_range = np.logspace(-9, 3, 13)
param_grid = dict( gamma=gamma_range,C=C_range)
grid = GridSearchCV(SVC(), param_grid=param_grid,verbose=2)
grid.fit(X_train, y_train)

Fitting 5 folds for each of 169 candidates, totalling 845 fits
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-09; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-08; total time=   0.0s
[CV] END ................................C=0.01, gamma=1e-07; total time=   0.0s
[CV] END ................................C=0.0

GridSearchCV(estimator=SVC(),
             param_grid={'C': array([1.e-02, 1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05,
       1.e+06, 1.e+07, 1.e+08, 1.e+09, 1.e+10]),
                         'gamma': array([1.e-09, 1.e-08, 1.e-07, 1.e-06, 1.e-05, 1.e-04, 1.e-03, 1.e-02,
       1.e-01, 1.e+00, 1.e+01, 1.e+02, 1.e+03])},
             verbose=2)

In [41]:
print("The best parameters are %s with a score of %0.2f"
      % (grid.best_params_, grid.best_score_))

The best parameters are {'C': 1000000.0, 'gamma': 1e-07} with a score of 0.94


In [42]:
y_predict = grid.predict(X_test)
print(confusion_matrix(y_predict,y_test))

[[ 33   3]
 [  6 114]]


In [43]:
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )

0.9423076923076923


In [44]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.92      0.85      0.88        39
           1       0.95      0.97      0.96       117

    accuracy                           0.94       156
   macro avg       0.93      0.91      0.92       156
weighted avg       0.94      0.94      0.94       156



In [45]:
params = {'C': [0.1,1, 10, 100], 'gamma': [1,0.1,0.01,0.001]}
print (params)
rgrid =  RandomizedSearchCV(SVC(), param_distributions=params, n_iter= 12,cv = 10,  verbose=2 )

rgrid.fit(X_train, y_train)

{'C': [0.1, 1, 10, 100], 'gamma': [1, 0.1, 0.01, 0.001]}
Fitting 10 folds for each of 12 candidates, totalling 120 fits
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END ...................................C=0.1, gamma=0.1; total time=   0.0s
[CV] END .................................C=0.1, gamma=0.001; total ti

RandomizedSearchCV(cv=10, estimator=SVC(), n_iter=12,
                   param_distributions={'C': [0.1, 1, 10, 100],
                                        'gamma': [1, 0.1, 0.01, 0.001]},
                   verbose=2)

In [46]:
print("The best parameters are %s with a score of %0.2f"
      % (rgrid.best_params_, rgrid.best_score_))

The best parameters are {'gamma': 0.01, 'C': 10} with a score of 0.94


In [47]:
y_predict = rgrid.predict(X_test)
print(confusion_matrix(y_predict,y_test))

[[ 35   2]
 [  4 115]]


In [48]:
accuracy = accuracy_score(y_predict,y_test)
print (accuracy )

0.9615384615384616


In [49]:
print(classification_report(y_test, y_predict))

              precision    recall  f1-score   support

           0       0.95      0.90      0.92        39
           1       0.97      0.98      0.97       117

    accuracy                           0.96       156
   macro avg       0.96      0.94      0.95       156
weighted avg       0.96      0.96      0.96       156

