1.Write a NumPy program to get the numpy version and show numpy build configuration.

In [2]:
import numpy as np

In [3]:
np.__version__

'1.24.3'

In [4]:
np.show_config()

blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/USER/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/USER/anaconda3\\Library\\in

2. Write a NumPy program to  get help on the add function.

In [5]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

3. Write a NumPy program to test whether none of the elements of a given array is zero.

In [6]:
n = np.array([1,2,3,4])


In [7]:
n

array([1, 2, 3, 4])

In [8]:
np.all(n)

True

In [9]:
n = np.array([0,1,2,3])

In [10]:
n

array([0, 1, 2, 3])

In [11]:
np.all(n)

False

4. Write a NumPy program to test whether any of the elements of a given array is non-zero.

In [12]:
n = np.array([1,0,0,0])

In [13]:
n

array([1, 0, 0, 0])

In [14]:
np.any(n)

True

In [15]:
n = np.array([0,0,0,0])

In [16]:
n

array([0, 0, 0, 0])

In [17]:
np.any(n)

False

5. Write a NumPy program to test a given array element-wise for finiteness (not infinity or not a Number).

In [18]:
n = np.array([0,1,np.nan,np.inf])

In [19]:
n

array([ 0.,  1., nan, inf])

In [20]:
np.isfinite(n)

array([ True,  True, False, False])

6. Write a NumPy program to test element-wise for positive or negative infinity.

In [21]:
n = np.array([0,1,np.nan,np.inf])

In [22]:
n

array([ 0.,  1., nan, inf])

In [23]:
np.isinf(n)

array([False, False, False,  True])

7. Write a NumPy program to test element-wise for NaN of a given array.

In [24]:
n = np.array([0,1,np.nan,np.inf])

In [25]:
n

array([ 0.,  1., nan, inf])

In [26]:
np.isnan(n)

array([False, False,  True, False])

8. Write a NumPy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

In [27]:
a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])       

In [28]:
a

array([1. +1.j, 1. +0.j, 4.5+0.j, 3. +0.j, 2. +0.j, 0. +2.j])

In [29]:
np.iscomplex(a)

array([ True, False, False, False, False,  True])

In [30]:
np.isreal(a)

array([False,  True,  True,  True,  True, False])

In [31]:
np.isscalar(3.1)

True

In [32]:
np.isscalar([3.1])

False

9. Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

In [33]:
x = np.array([3, 5])
y = np.array([2, 5])

In [34]:
x

array([3, 5])

In [35]:
y

array([2, 5])

In [36]:
np.greater(x,y)

array([ True, False])

In [37]:
np.greater_equal(x,y)

array([ True,  True])

In [38]:
np.less(x,y)

array([False, False])

In [39]:
np.less_equal(x,y)

array([False,  True])

10. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays.

In [40]:
x = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])


In [41]:
x

array([  72,   79,   85,   90,  150, -135,  120,  -10,   60,  100])

In [42]:
y

array([  72.      ,   79.      ,   85.      ,   90.      ,  150.      ,
       -135.      ,  120.      ,  -10.      ,   60.      ,  100.000001])

In [43]:
np.equal(x,y)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [44]:
np.allclose(x,y)

True

11. Write a NumPy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupied by the array.

In [45]:
a = np.array([1,7,13,105])

In [46]:
a

array([  1,   7,  13, 105])

In [47]:
(a.size *a.itemsize) 

16

12. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives.

In [48]:
array = np.zeros(10)

In [49]:
array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [50]:
array = np.ones(10)

In [51]:
array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
array = np.ones(10)*5

In [53]:
array

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

13. Write a NumPy program to create an array of the integers from 30 to70.

In [55]:
array = np.arange(30,71)

In [56]:
array

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63,
       64, 65, 66, 67, 68, 69, 70])

 14. Write a NumPy program to create an array of all the even integers from 30 to 70.

In [57]:
array = np.arange(30,71,2)

In [58]:
array

array([30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62,
       64, 66, 68, 70])