1. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

Expected Output:

Original List: [12.23, 13.32, 100, 36.32]

One-dimensional NumPy array: [ 12.23 13.32 100. 36.32]

In [2]:
import numpy as np

In [6]:
a=[12.23, 13.32, 100, 36.32]

In [9]:
b = np.array(a)

In [11]:
print(b)

[ 12.23  13.32 100.    36.32]


2.Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.  
Expected Output:

[[ 2 3 4]

[ 5 6 7]

[ 8 9 10]]

In [12]:
a = np.arange(2,11).reshape(3,3)

In [13]:
print(a)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11. 

[ 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

Update sixth value to 11

[ 0. 0. 0. 0. 0. 0. 11. 0. 0. 0.]

In [14]:
a = np.zeros(10)

In [15]:
print(a)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [16]:
a[6] = 11

In [17]:
print(a)

[ 0.  0.  0.  0.  0.  0. 11.  0.  0.  0.]


4. Write a NumPy program to create an array with values ranging from 12 to 38. 

Expected Output:

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

In [18]:
a = np.arange(12,39)

In [19]:
print(a)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38]


5. Write a NumPy program to reverse an array (first element becomes last). 
 
Original array:
    

    [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37]

    Reverse array:

        [37 36 35 34 33 32 31 30 29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]

In [20]:
a = np.arange(12,39)

In [21]:
a[::-1]

array([38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22,
       21, 20, 19, 18, 17, 16, 15, 14, 13, 12])

6. Write a NumPy program to convert an array to a float type.  
Sample output:
Original array
[1, 2, 3, 4]
Array converted to a float type:
[ 1. 2. 3. 4.]

In [23]:
a = [1,2,3,4]

In [24]:
print(np.asfarray(a))

[1. 2. 3. 4.]


7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside. 

Expected Output:
Original array:

[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]

1 on the border and 0 inside in the array

[[ 1. 1. 1. 1. 1.]
...................
[ 1. 1. 1. 1. 1.]]


In [25]:
a = np.ones((5,5))

In [26]:
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [30]:
a[1:-1,1:-1] = 0

In [31]:
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


8. Write a NumPy program to add a border (filled with 0's) around an existing array.  
Expected Output:

Original array:

[[ 1. 1. 1.]
[ 1. 1. 1.]
[ 1. 1. 1.]]

1 on the border and 0 inside in the array

[[ 0. 0. 0. 0. 0.]
...........
[ 0. 0. 0. 0. 0.]]

In [85]:
a = np.zeros((5,5))

In [86]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [89]:
a[1:-1,1:-1] = 1

In [90]:
print(a)

[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


9. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.  
Checkerboard pattern:
Checkerboard pattern:

[[0 1 0 1 0 1 0 1]

 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]
 
 [0 1 0 1 0 1 0 1]
 
 [1 0 1 0 1 0 1 0]]


In [93]:
a = np.ones((8,8))

In [94]:
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [113]:
a[1::2,::2] = 0
a[::2,1::2] = 0

In [114]:
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


10. Write a NumPy program to convert a list and tuple into arrays. 
 
 List to array:
 
[1 2 3 4 5 6 7 8]

Tuple to array:

[[8 4 6]

[1 2 3]]


In [128]:
a = np.array([1,2,3,4,5,6,7,8])

In [129]:
print(a)

[1 2 3 4 5 6 7 8]


In [133]:
b = np.array(([8,4,6],[1,2,3]))

In [134]:
print(b)

[[8 4 6]
 [1 2 3]]


11. Write a NumPy program to append values to the end of an array.  

Expected Output:

Original array:

[10, 20, 30]

After append values to the end of the array:

[10 20 30 40 50 60 70 80 90]

In [188]:
a = np.array([10,20,30])

In [189]:
a_append = np.append(a,[[40,50,60],[70,80,90]])

In [190]:
print(a_append)

[10 20 30 40 50 60 70 80 90]


12. Write a NumPy program to create an empty and a full array. 

 Expected Output:
 
[ 6.93270651e-310 1.59262180e-316 6.93270559e-310 6.93270665e-310]

[ 6.93270667e-310 6.93270671e-310 6.93270668e-310 6.93270483e-310]

[ 6.93270668e-310 6.93270671e-310 6.93270370e-310 6.93270488e-310]]

[[6 6 6]

[6 6 6]

[6 6 6]]

In [192]:
a = np.empty((3,4))

In [193]:
print(a)

[[ 0.    4.    3.46  2.  ]
 [ 2.18 -3.   -2.18 -3.  ]
 [-3.46  2.    0.    4.  ]]


In [194]:
b = np.full((3,3),6)

In [195]:
print(b)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


13. Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

Sample Array [0, 12, 45.21 ,34, 99.91]

Expected Output:

Values in Fahrenheit degrees:

[ 0. 12. 45.21 34. 99.91]

Values in Centigrade degrees:

[-17.77777778 -11.11111111 7.33888889 1.11111111 37.72777778]

In [19]:
a = np.array([0, 12, 45.21 ,34, 99.91])

In [23]:
print(5*a/9 - 5*32/9)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


14. Write a NumPy program to find the real and imaginary parts of an array of complex numbers.  

Expected Output:

Original array [ 1.00000000+0.j 0.70710678+0.70710678j]

Real part of the array:

[ 1. 0.70710678]

Imaginary part of the array:

[ 0. 0.70710678]

In [24]:
a = np.sqrt([1+0j])
b = np.sqrt([0+1j])

In [32]:
print(a.real)

[1.]


In [33]:
print(b.real)

[0.70710678]


In [34]:
print(a.imag)

[0.]


In [35]:
print(b.imag)

[0.70710678]
