Dimension Reduction – LDA 
Case Study -1 (CS 42)
Case Study


Objective:



•	Understand and practice linear discriminant analysis using scikit learn.





Questions:



1.	We shall use the same dataset used in previous assignment - digits. Make a 80-20 train/test split.

[Hint: Explore datasets module from scikit learn]



2.	Using scikit learn perform a LDA on the dataset. Find out the number of components in the projected subspace.

[Hint: Refer to discriminant analysis module of scikit learn]



3.	Transform the dataset and fit a logistic regression and observe the accuracy. Compare it with the previous model based on PCA in terms of accuracy and model complexity.

[Hint: Project both the train and test samples to the new subspace]

In [1]:
import sklearn
from sklearn.datasets import  load_digits
from sklearn.model_selection import train_test_split
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as lda
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np

In [2]:
digits = load_digits()

X = digits.data
y = digits.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)
print(X_train.shape)

(1437, 64)


In [4]:
sklearn_lda = lda()
sklearn_lda.fit(X_train,y_train)
X_train = sklearn_lda.transform(X_train)
print (X_train.shape)
print("Number of components in transformed shape {}".format(X_train.shape[1]))

(1437, 9)
Number of components in transformed shape 9


In [5]:
X_test =sklearn_lda.transform(X_test)
print(X_test.shape)

(360, 9)


In [6]:
lr = LogisticRegression()
lr.fit(X_train,y_train)
y_predict = lr.predict(X_test)

In [7]:
print (accuracy_score(y_predict,y_test))

0.95


In [8]:
conf_mat =confusion_matrix(y_predict,y_test)
print (conf_mat)

[[41  0  0  0  0  0  0  0  0  0]
 [ 0 32  1  0  0  1  0  1  0  0]
 [ 0  0 35  0  0  0  0  0  0  0]
 [ 0  0  0 40  0  0  0  0  0  0]
 [ 1  1  0  0 38  0  0  1  0  1]
 [ 0  0  0  0  0 28  0  0  1  1]
 [ 1  0  0  0  0  0 37  0  0  0]
 [ 0  0  0  0  0  0  0 34  0  0]
 [ 0  1  0  1  0  0  0  0 26  1]
 [ 0  1  0  0  0  1  0  1  2 31]]


In [9]:
print (classification_report(y_predict,y_test))

              precision    recall  f1-score   support

           0       0.95      1.00      0.98        41
           1       0.91      0.91      0.91        35
           2       0.97      1.00      0.99        35
           3       0.98      1.00      0.99        40
           4       1.00      0.90      0.95        42
           5       0.93      0.93      0.93        30
           6       1.00      0.97      0.99        38
           7       0.92      1.00      0.96        34
           8       0.90      0.90      0.90        29
           9       0.91      0.86      0.89        36

    accuracy                           0.95       360
   macro avg       0.95      0.95      0.95       360
weighted avg       0.95      0.95      0.95       360



In [10]:
np.where(y_predict != y_test)

(array([ 21,  58,  88, 108, 130, 155, 172, 173, 174, 178, 193, 208, 249,
        281, 285, 320, 321, 347], dtype=int64),)